### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by ConnorTurnbull** [ConnorTurnbull/Project-5-Build-an-E-Commerce-Website-with-Javascript#7]
Hey @AccessiT3ch ,

I'm having an issue with form validation on the cart page that I can't quite get my head around. 

What I think is happening is that the form is being submitted without the data validation actually being checked. 

If I test the validation itself by returning or commenting out before the submission event listener, then as far as i can tell the validation itself is working correctly (though any hints/tips much appreciated). However, if I pass the form validation function into the event listener, the form just submits regardless of whether it's passing validation or not or even if anything has been entered, whereas I need the form submission to rely on the users input passing form validation.

Hope that makes sense.

[cart.js](https://github.com/ConnorTurnbull/Project-5/blob/cart-page/front/js/cart.js) (line 123 onward)

Cheers!

**Comment by AccessiT3ch** [comment]
Hey @ConnorTurnbull it looks like the values are being checked for validation, but it doesn't look like you're doing anything with the information once you have validated. You might consider returning a `false` from the validation function if things are invalid, and `true` if everything checks out. Then you can use that returned boolean in an if conditional to return out of the form submit event listener or throw an error to prevent the function from sending the fetch request.

```js
...
const isValid = validateInput() // returns a true or false
if (!isValid) {
  throw new Error ('Invalid form data');
}
// you won't need an else here b/c the code with exit the function when throwing or returning like this
...
```

**Comment by ConnorTurnbull** [comment]
Hi @AccessiT3ch, I've tried what you've suggested above but i still have the same problem. 

Also strangely I now can't get it to show the order confirmation page after order submission even if the form is filled out correctly.  It's almost acting as if the page is getting refreshed, no network request made or anything and yet this wasn't the case yesterday so I've no idea what's going on.

Edit: So i've managed to get a bit further with this by changing the event listener to 'click' rather than 'submit' so I now have proper form validation working again but even with a fully validated form the error is still thrown by isValid

**Comment by ConnorTurnbull** [comment]
@AccessiT3ch console.log of isValid is just returning undefined rather than true/false so maybe something there?

**Comment by ConnorTurnbull** [comment]
@AccessiT3ch managed to fix it by adding return false to all the fail conditions of the input validation and return true otherwise.

[cart.js](https://github.com/ConnorTurnbull/Project-5/blob/52cb477a2b0ea9ebf9f060498e380908253908a5/front/js/cart.js)

**Comment by AccessiT3ch** [comment]
Awesome! How's it looking?? Everything good to present?

**Comment by ConnorTurnbull** [comment]
Yeah I think it's okay now, was only the form validation to sort out as far
as I've noticed.
